### ISSUE TITLE
خفن‌ناک :D

### ISSUE THREAD

**Issue by ghost** [fadavi/emacs#1]
سلام. خوبین؟
میگم من کشته مرده اون خط های ۴ تا ۱۱ شدم اصن
ایده‌ی خیلی باحالی بود.
لایسنس ایده‌تون چیه؟ :D
قبلا منو وسوسه کردین رفتم آی۳ نصب کردم. الانم گمونم وسوسه بشم برم ایمکس نصب کنم خخخ

**Comment by fadavi** [comment]
به‌به سلام رسول جان.. خوبم شما چطوری؟
پروانه نداره، با خیال راحت استفاده کن!

در مورد ایمکس، یه لحظه هم شک نکن!!
